version: '2.2'

volumes:
  database:
  host_keys:
  authorized_keys:

services:
  sample_database:
    image: docker.io/mariadb:10.5.8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: someone
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: demo
      # https://github.com/docker-library/mariadb/issues/251
      # https://github.com/docker-library/mariadb/issues/262#issuecomment-536405303
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
    - database:/var/lib/mysql:rw
  sshd:
    build: .
    image: docker.io/fphammerle/mysqldump-sshd
    environment:
      MYSQLDUMP_ARGS: >-
        --host=sample_database
        --user=someone
        --password=secret
        --skip-add-drop-table
        --skip-comments
        --skip-dump-date
        --databases demo
    volumes:
    - host_keys:/etc/ssh/host_keys:rw
    - authorized_keys:/home/dump/.ssh:ro
    read_only: true
    ports: ['127.0.0.1:2200:2200']
    cap_drop: [ALL]
    # strace
    # cap_add: [SYS_PTRACE]
    security_opt: [no-new-privileges]
    # docker-compose >=2.2,<3
    cpus: 0.2
    mem_limit: 64M

# https://docs.docker.com/compose/compose-file/compose-file-v2/
